# there is an upstream server called client which is located at service/host called client at 3000 port.
upstream client {
    server client:3000;
}

upstream api {
    server api:5000;
}

## Main body and configuration of nginx
server {
    listen 80;

    ## if incoming request has /, route it to the react/client upstream server
    location / {
        proxy_pass http://client;
    }

    ## To resolve warning on console which was due to not have websocket connection on 
    ## nginx to the react server which can notify the browser in case of any change in
    ## the react code. It is specific only for dev. You can create another default.conf
    ## for prod dockerfile without below section.
    location /sockjs-node {
        proxy_pass http://client;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }

    ## if incoming request has /api, route it to the api upstream server after chopping/rewritting
    ## /api/abc to just  /abc
    location /api {
        rewrite /api/(.*) /$1 break;
        proxy_pass http://api;
    }
}
