FROM node:16-alpine
## nodemon uses chokidar; polling is required for file changes injected by Skaffold sync.
ENV CHOKIDAR_USEPOLLING=true
WORKDIR "/app"
COPY ./package.json ./
RUN npm install
COPY . .
CMD ["npm", "run", "dev"]
